spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

transfer:
  enable-different-currency-transfer: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false