version: '3.8'

services:
  eureka-service:
    build: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  user-service:
    build: ./user-service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-service
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      # todo use real db config
      - SPRING_DATASOURCE_URL=jdbc:mysql://prod-db-host:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=prod_user
      - SPRING_DATASOURCE_PASSWORD=prod_password

  moneytransfer-service:
    build: ./moneytransfer-service
    ports:
      - "8089:8089"
    depends_on:
      - eureka-service
      - user-service
      - mysql
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      # todo use real db config
      - SPRING_DATASOURCE_URL=jdbc:mysql://prod-db-host:3306/money_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=prod_user
      - SPRING_DATASOURCE_PASSWORD=prod_password

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - user-service
      - moneytransfer-service
    networks:
      - mynetwork
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/

volumes:
  mysql-data:

networks:
  mynetwork:
