spring:
  datasource:
    url: jdbc:h2:mem:transferdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

transfer:
  enable-different-currency-transfer: false